apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring-system
type: Opaque
stringData:
  VM_ADMIN_USER: "VM_ADMIN_USER"
  VM_ADMIN_PASSWORD: "VM_ADMIN_PASSWORD"
  GRAFANA_ADMIN_USER: "GRAFANA_ADMIN_USER"
  GRAFANA_ADMIN_PASSWORD: "GRAFANA_ADMIN_PASSWORD"