apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm-backend
  namespace: monitoring-system
spec:
  nodeSelector:
    kubernetes.io/hostname: soleimani-ha2
  retentionPeriod: "14d"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi