apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring-system
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m
    route:
      receiver: "alert-viewer-webhook"
      group_by: ['alertname', 'job']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1m
    receivers:
      - name: "alert-viewer-webhook"
        webhook_configs:
          - url: "http://alert-viewer.monitoring-system.svc.cluster.local:8080/webhook"
            send_resolved: false
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: alertmanager
  namespace: monitoring-system
spec:
  replicaCount: 1
  selectAllByDefault: true
  configSecret: alertmanager-config
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "64Mi"