apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring-system
spec:
  replicaCount: 1
  selectAllByDefault: true
  serviceScrapeNamespaceSelector: {}
  scrapeInterval: 30s
  remoteWrite:
    - url: "http://vmsingle-vm-backend.monitoring-system.svc.cluster.local:8428/api/v1/write"
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"