apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmsingle-scrape
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: vmsingle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmsingle
  jobLabel: app.kubernetes.io/name
  endpoints:
    - port: http
      path: /metrics
      interval: 20s
      scrapeTimeout: 10s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmagent-scrape
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: vmagent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmagent
  jobLabel: app.kubernetes.io/name
  endpoints:
    - port: http
      path: /metrics
      interval: 20s
      scrapeTimeout: 10s
