apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmoperator-scrape
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  jobLabel: app.kubernetes.io/name
  endpoints:
    - targetPort: 8080
      path: /metrics
      interval: 20s
      scrapeTimeout: 10s